AllCops:
  Exclude:
    - bin/*
    - db/seeds.rb
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/**
    - app/channels/application_cable/**
    - spec/helpers/application_helper_spec.rb
    - node_modules/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
